# If the bot should search for URLs in sent messages
search_messages = true

# Platforms that are supported by the bot
active_platforms = ["spotify", "youtube"]

[spotify]
# Used to obtain an api key
# https://developer.spotify.com/documentation/web-api/tutorials/getting-started#create-an-app
client_id = ""
# Used to obtain an api key
# https://developer.spotify.com/documentation/web-api/tutorials/getting-started#create-an-app
client_secret = ""
